version: "3.2"

services:
  cv-19-res-support-api-v3:
    image: cv-19-res-support-api-v3
    build:
      context: cv19ResSupportV3/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=devdb;Username=postgres;Password=mypassword
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - dev-database
  dev-database:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=devdb
    image: postgres:12

  cv-19-res-support-api-v3-test:
    image: cv-19-res-support-api-v3-test
    build:
      context: .
      dockerfile: cv19ResSupportV3.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
      - ASPNETCORE_ENVIRONMENT=Test
    links:
      - test-database
  test-database:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=testdb
    image: postgres:12
